version: '3'
services:
  postgres:
    image: "postgres:13.7"
    container_name: ujar-basics-restful-bookstore-postgres
    restart: unless-stopped
    ports :
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=sa_test_db
